export interface Product {
  id: number;
  name: string;
  price: number;
  description: string;
}

export const products = [
  {
    id: 1,
    name: 'Apple Dock Connector to VGA Adapter (30-pin)',
    price: 24.99,
    description: 'Apple Dock Connector to VGA Adapter (30-pin)',
    url:'https://www.amazon.com/Apple-Dock-Connector-Adapter-30-pin/dp/B0052XN17Y/ref=sr_1_49?qid=1647164139&refinements=p_89%3AApple&rnid=2528832011&s=electronics&sr=1-49',
    image1:'https://m.media-amazon.com/images/I/61MKdpwqM9L._AC_SX569_.jpg',
    image2:'https://m.media-amazon.com/images/I/51KmHdRhR5L._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/610QHF9C1TL._AC_SX569_.jpg',
    rating:'4.png',
    rating_text: 4,
    likes: 0,
    show: true,
    categoryId: 1,
    isDisabled: false
  },
  {
    id: 2,
    name: 'Apple Watch Series 7 GPS, 41mm Green Aluminum Case with Clover Sport Band - Regular',
    price: 749,
    description: 'A great phone with one of the best cameras',
    url:'https://www.amazon.com/Apple-Watch-Green-Aluminum-Clover/dp/B09HF1DC1J?ref_=ast_sto_dp&th=1&psc=1',
    image1:'https://m.media-amazon.com/images/I/71MQd0o+uHL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/81jfIU6phrL._AC_SX466_.jpg',
    image3:'https://m.media-amazon.com/images/I/71buMKwU1RL._AC_SX466_.jpg',
    rating:'5.png',
    rating_text: 5,
    likes: 0,
    show: true,
    categoryId: 1,
    isDisabled: false
  },
  {
    id: 3,
    name: 'Apple AirPods (3rd Generation)',
    price: 179,
    description: 'Spatial audio with dynamic head tracking places sound all around you. Adaptive EQ automatically tunes music to your ears. All-new contoured design',
    url:'https://www.amazon.com/Apple-MME73AM-A-AirPods-3rd-Generation/dp/B09JQL3NWT?ref_=ast_sto_dp',
    image1:'https://m.media-amazon.com/images/I/61ZRU9gnbxL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/619prszLWuL._AC_SX466_.jpg',
    image3:'https://m.media-amazon.com/images/I/61xEN4thgIL._AC_SX466_.jpg',
    rating:'5.png',
    rating_text: 5,
    likes: 0,
    show: true,
    categoryId: 1,
    isDisabled: false
  },
  {
    id: 4,
    name: 'HD 1080p Pet Camera，Dog Camera 360° Pet Monitor Indoor Cat Camera with Night Vision and Two Way Audio',
    price: 40.99,
    description: 'Smart Home Camera Usually used for business and home security,as well as baby monitors,indoor cameras for toddlers,and pet surveillance cameras,for motion detection and recording to monitor the elderly. With 1080p full HD 360 degrees panoramic view and 3D navigation smart pan or tilt, you can always see any angle and never miss a moment. Remote monitor, iOS, Android application. Only supports 2.4G WiFi (5G WiFi is not supported).',
    url:'https://www.amazon.com/dp/B07M7DW3TW/ref=s9_acsd_al_bw_c2_x_1_t?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=M2JPN5SHXYM2G5SWR8GZ&pf_rd_t=101&pf_rd_p=b009b02a-d3fc-4c11-ad97-1768be299efc&pf_rd_i=21221447011',
    image1:'https://m.media-amazon.com/images/I/61TPL-TnQfL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/716JWeEbBhL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/71EEhGsO6lL._AC_SX679_.jpg',
    rating:'4.png',
    rating_text: 4,
    likes: 0,
    show: true,
    categoryId: 2,
    isDisabled: false
  },
  {
    id: 5,
    name: 'WOPET SmartFeeder,Automatic Pet Dog and Cat Feeder,6-Meal Auto Pet Feeder with Timer Programmable,HD Camera for Voice and Video Recording,Wi-Fi Enabled App for iPhone and Android',
    price: 179,
    description: 'Smartphone Controls Feeding:Remotely set times to feed your pet automatically,You can set 1-6 meals per day and up to 20 portions of dry food per meal depending on your pet’s needs. Customized healthy diet for your cats and dogs,Support 2.4GHz network only.',
    url:'https://www.amazon.com/dp/B07N5BBFZY/ref=s9_acsd_al_bw_c2_x_2_t?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=M2JPN5SHXYM2G5SWR8GZ&pf_rd_t=101&pf_rd_p=b009b02a-d3fc-4c11-ad97-1768be299efc&pf_rd_i=21221447011&th=1',
    image1:'https://m.media-amazon.com/images/I/61xH7kDpT+S._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/71fUBBCOeyL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/71wtRXGxb1S._AC_SX679_.jpg',
    rating:'4.5.png',
    rating_text: 4.5,
    likes: 0,
    show: true,
    categoryId: 2,
    isDisabled: false
  },
  {
    id: 6,
    name: '14 Sizes Crochet Hooks Set,2mm(B)-10mm(N) Ergonomic Crochet Hooks with Case for Arthritic Hands,Extra Long Crochet Needles',
    price: 17.99,
    description: 'Great Value You get 14 Ergonomic Crochet Hooks,9 Yarn Needles,10 Stitch Markers,1 Scissors& Case.Fantastic value for your buck.Stitch markers,scissors and yarn needles are a great bonus in a convenient case.The crochet hook set is a great crochet starter kit.',
    url:'https://www.amazon.com/Sizes-Crochet-Ergonomic-Arthritic-Needles/dp/B07RNNL6RT/ref=sr_1_2?qid=1647163898&s=arts-crafts-intl-ship&sr=1-2',
    image1:'https://m.media-amazon.com/images/I/613NGjZe59L._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/61GFJV4YlWL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/61vk0zlOsJL._AC_SX679_.jpg',
    rating:'5.png',
    rating_text: 5,
    likes: 0,
    show: true,
    categoryId: 3,
    isDisabled: false
  },
  {
    id: 7,
    name: 'Amoco 3PCS Adjustable Knitting Loop Crochet Loop Ring Knitting Accessories Yarn Guide Finger Holder Knitting Thimble Knitting Loop Ring for DIY Knitting Crafts',
    price: 10.99,
    description: 'High quality material:The knitting loop ring is made of high-quality silver-plated with crocheting crocheting embossed craftsmanship,not rust,durable,reusable and adjustable.',
    url:'https://www.amazon.com/Amoco-Adjustable-Knitting-Crochet-Accessories/dp/B08PNWGGVY/ref=sr_1_1_sspa?qid=1647163898&s=arts-crafts-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExRzJYUUlTMzc2N00xJmVuY3J5cHRlZElkPUEwMDc0MjIwMTNSVDVJWFhSSzlVMiZlbmNyeXB0ZWRBZElkPUEwOTU2Nzc5MU5JRjNWVkVGUFVWSCZ3aWRnZXROYW1lPXNwX2F0Zl9icm93c2UmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
    image1:'https://m.media-amazon.com/images/I/71NPDIFf5PL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/613VGjdweaL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/61HleTWjtbL._AC_SX679_.jpg',
    rating:'4.png',
    rating_text: 4,
    likes: 0,
    show: true,
    categoryId: 3,
    isDisabled: false
  },
  {
    id: 8,
    name: 'Tablet 10 inch Android 11 Cellular 4G LTE Tablet PC 2 Sim Slot, 4GB RAM 128GB Storage, Google Certified Octa-Core Tablet with Keyboard Pen Case 13+5 MP Camera,Phone Call,Bluetooth WiFi GPS Video',
    price: 169.99,
    description: '4G LTE phone tablet Comes with Bluetooth Keyboard, Pen, Wireless Mouse and foldable protective case, it can flexibly turn tablet into a laptop and smartphone mode, make it 2 in 1 Tablet.',
    url:'https://www.amazon.com/Cellular-Certified-Octa-Core-Keyboard-Bluetooth/dp/B09MKXYBPG/ref=sr_1_1_sspa?qid=1647163971&s=computers-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFXRUNOSzlZOEgxUU4mZW5jcnlwdGVkSWQ9QTA3NzI3MDVCSjNaT0ZVN0RWWlkmZW5jcnlwdGVkQWRJZD1BMDc2ODU1OTNVRVhMMVJMS0VaOFkmd2lkZ2V0TmFtZT1zcF9hdGZfYnJvd3NlJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==',
    image1:'https://m.media-amazon.com/images/I/71QSV2AmJKL._AC_SX569_.jpg',
    image2:'https://m.media-amazon.com/images/I/71ebABYJ-uL._AC_SY450_.jpg',
    image3:'https://m.media-amazon.com/images/I/712cTnMApXL._AC_SY450_.jpg',
    rating:'3.5.png',
    rating_text: 3.5,
    likes: 0,
    show: true,
    categoryId: 4,
    isDisabled: false
  },
  {
    id: 9,
    name: 'Lenovo IdeaPad 3 11 Chromebook Laptop, 11.6" HD Display, Intel Celeron N4020, 4GB RAM, 64GB Storage, Intel UHD Graphics 600, Chrome OS',
    price: 168,
    description: 'No setup required. Log in to your Chromebook laptop with your Google account and you are ready to go. Easy access to collaborative tools on G Suite and the full library of apps on Google Play.',
    url:'https://www.amazon.com/Lenovo-Chromebook-Processor-Graphics-82BA0003US/dp/B087YW8FQB/ref=sr_1_2?qid=1647163971&s=computers-intl-ship&sr=1-2',
    image1:'https://m.media-amazon.com/images/I/71XIwK5G75L._AC_SX569_.jpg',
    image2:'https://m.media-amazon.com/images/I/61DBhNhTpYL._AC_SY450_.jpg',
    image3:'https://m.media-amazon.com/images/I/71+YKl8hMjL._AC_SY450_.jpg',
    rating:'4.5.png',
    rating_text: 4.5,
    likes: 0,
    show: true,
    categoryId: 4,
    isDisabled: false
  },
  {
    id: 10,
    name: 'Lenovo Flex 5 Laptop, 14.0" FHD Touch Display, AMD Ryzen 5 5500U, 16GB RAM, 256GB Storage, AMD Radeon Graphics, Windows 11 Home',
    price: 619,
    description: 'Powered by an AMD Ryzen 5 5500U mobile processor with Radeon graphics, this portable notebook computer has 16GB DDR4 RAM and 256GB NVMe SSD Storage.',
    url:'https://www.amazon.com/Lenovo-Processor-Graphics-82HU00JWUS-Graphite/dp/B09BG96KFJ/ref=sr_1_4?qid=1647163971&s=computers-intl-ship&sr=1-4&th=1',
    image1:'https://m.media-amazon.com/images/I/71zZiQGzc5L._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/818B97p+vcL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/71QjZ06DaFL._AC_SX679_.jpg',
    rating:'4.5.png',
    rating_text: 4.5,
    likes: 0,
    show: true,
    categoryId: 4,
    isDisabled: false
  },
  {
    id: 11,
    name: 'Apple AirTag',
    price: 99,
    description: 'Keep track of and find your items alongside friends and devices in the Find My app. Simple one-tap setup instantly connects AirTag with your iPhone or iPad',
    url:'https://www.amazon.com/dp/B0933BVK6T/ref=fs_a_md_0',
    image1:'https://m.media-amazon.com/images/I/713xuNx00oS._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/71JJueCRWJS._AC_SX466_.jpg',
    image3:'https://m.media-amazon.com/images/I/81Lq1AfCYpS._AC_SX466_.jpg',
    rating:'4.5.png',
    rating_text: 4.5,
    likes: 0,
    show: true,
    categoryId: 1,
    isDisabled: false
  },
  {
    id: 12,
    name: 'Apple Magic Mouse (Wireless, Rechargable) - Silver',
    price: 79,
    description: 'Magic Mouse is wireless and rechargeable, with an optimized foot design that lets it glide smoothly across your desk.',
    url:'https://www.amazon.com/Apple-Magic-Mouse-Wireless-Rechargable/dp/B09BRD98T4?ref_=ast_sto_dp&th=1&psc=1',
    image1:'https://m.media-amazon.com/images/I/61BZ5N9n4IL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/513H49gKsjL._AC_SY500_.jpg',
    image3:'https://m.media-amazon.com/images/I/818tvn4YTlL._AC_SY500_.jpg',
    rating:'4.5.png',
    rating_text: 4.5,
    likes: 0,
    show: true,
    categoryId: 1,
    isDisabled: false
  },
  {
    id: 13,
    name: 'PetSafe ScoopFree Self Cleaning Cat Litter Box Systems - No More Scooping - 2nd Generation or Smart WiFi Connected, iOS/Android App with Health Counter - Automatic Cat Litter Box, Crystal Cat Litter',
    price: 249.95,
    description: 'APP-CONNECTED LITTER BOX: This litter box is connected to the My PetSafe app on your smart phone so you can monitor your cat’s health and her litter box from anywhere, even when you’re not home.',
    url:'https://www.amazon.com/PetSafe-ScoopFree-Covered-Cleaning-Litter/dp/B087C7K4CP/ref=lp_21221447011_1_12?th=1',
    image1:'https://m.media-amazon.com/images/I/81Y+XBTtB-L._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/716ro9WFoOL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/818NhILH20L._AC_SX679_.jpg',
    rating:'4.png',
    rating_text: 4,
    likes: 0,
    show: true,
    categoryId: 2,
    isDisabled: false
  },
  {
    id: 14,
    name: 'Chintu Automatic Cat Feeder Auto Cat Food Dispenser - Portion Control Pet Dry Food Dispenser for Small Dog, Programmable Timed Smart Cat Feeder with Voice Reminder',
    price: 42.99,
    description: 'No more pre-dawn wake up calls, or worry when you are overtime at night! Easy to program this automatic cat feeder with timer to dispense food in right time. No matter when and where you are, you can feed your pet effortlessly with this automatic pet feeder. The timed feeder for cats and dogs is a perfect choice for you when going out for work or have a short trip. Reset once a week to make the time more accurate.',
    url:'https://www.amazon.com/Chintu-Automatic-Cat-Feeder-Timer/dp/B08ND958NF/ref=sr_1_15?qid=1647186369&sr=8-15&srs=21221447011',
    image1:'https://m.media-amazon.com/images/I/71GMQXJTjnL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/71LJYkMdN3L._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/71G7k6pqaPL._AC_SX679_.jpg',
    rating:'4.png',
    rating_text: 4,
    likes: 0,
    show: true,
    categoryId: 2,
    isDisabled: false
  },
  {
    id: 15,
    name: 'Petcube Play 2 Wi-Fi Pet Camera with Laser Toy & Alexa Built-In, for Cats & Dogs. 1080P HD Video, 160° Full-Room View, 2-Way Audio, Sound/Motion Alerts, Night Vision, Pet Monitoring App',
    price: 99.95,
    description: '24/7 Ultimate pet monitoring – With Petcube Play 2 Wi-Fi pet cam, check on your pet anytime form your phone with 1080p HD video, 160° utlra-wide-angle view, and night vision. See up close with 4x zoom. Get real-time sound and motion alerts.',
    url:'https://www.amazon.com/Petcube-Camera-Built-Full-Room-Monitoring/dp/B07R3G87RG/ref=sr_1_16?qid=1647186369&sr=8-16&srs=21221447011',
    image1:'https://m.media-amazon.com/images/I/81LNPCsT2OL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/81k2TA3yNvL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/81cS6EF-qDL._AC_SX679_.jpg',
    rating:'4.png',
    rating_text: 4,
    likes: 0,
    show: true,
    categoryId: 2,
    isDisabled: false
  },
  {
    id: 16,
    name: 'TYH Supplies 20 Skeins 44 Yard Acrylic Yarn Assorted Colors Skeins - Perfect for Mini Knitting and Crochet Project',
    price: 17.99,
    description: '100% Acrylic Yarn 22-Yard Mini Skeins - You get a large variety of favorite 20 different colors perfect for all your knitting, crocheting, and crafts projects.',
    url:'https://www.amazon.com/TYH-Supplies-Acrylic-Assorted-Colors/dp/B072LCC84Z/ref=sr_1_1_sspa?c=ts&keywords=Knitting+%26+Crochet+Supplies&qid=1647186648&s=arts-crafts&sr=1-1-spons&ts_id=12897221&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExQ0VPSEpWVEMxRDJBJmVuY3J5cHRlZElkPUEwMjIyMzkyM0FCSjMwQVA4SEtPViZlbmNyeXB0ZWRBZElkPUEwNTA5OTg3M0hLUkhLQVU0VElPSiZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=',
    image1:'https://m.media-amazon.com/images/I/91l1N0e5cAL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/71qZ3taEZHL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/71Cp6qRFIwL._AC_SX679_.jpg',
    rating:'4.png',
    rating_text: 4,
    likes: 0,
    show: true,
    categoryId: 3,
    isDisabled: false
  },
  {
    id: 17,
    name: 'Coopay Warm Crochet Hooks for Grandmother, Art Aluminum Soft Grip Crochet Needles for Crocheting, Knitting Hook for Crochet Yarn Craft - Premium Knitting & Crochet Supplies',
    price: 9.29,
    description: 'Our crochet handle is made of durable and soft material, well crafted and sturdy, to avoid contact between the palm of your hand and the cold crochet hook during the crocheting process, while giving you a good grip. Let you enjoy crocheting project more with warm ergonomic crochet hook set.',
    url:'https://www.amazon.com/Coopay-Grandmother-Aluminum-Crocheting-Knitting/dp/B08QYWVZ9Q/ref=sr_1_2?c=ts&keywords=Knitting+%26+Crochet+Supplies&qid=1647186648&s=arts-crafts&sr=1-2&ts_id=12897221',
    image1:'https://m.media-amazon.com/images/I/71+eJ8gdcGL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/81Y1DGxkzpL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/71IGMaNfMmS._AC_SX679_.jpg',
    rating:'4.5.png',
    rating_text: 4.5,
    likes: 0,
    show: true,
    categoryId: 3,
    isDisabled: false
  },
  {
    id: 18,
    name: 'Coopay Huge Crochet Bag Knitting Bag for Crochet Hooks, Portable Yarn Bag Travel Crochet Bag with Removable Inner Divider for Crochet Yarn & Knitting Crochet Supplies -Ideal Knitting Gifts',
    price: 29.99,
    description: 'This knitting bag is large enough for all your crochet hooks, yarn bowls, knitting looms, circular needles and yarn. We specially design a large storage space for your unfinished project. Keep everything you need in one bag.',
    url:'https://www.amazon.com/Coopay-Knitting-Portable-Removable-Supplies/dp/B09JP9DLYQ/ref=sr_1_4?c=ts&keywords=Knitting+%26+Crochet+Supplies&qid=1647186648&s=arts-crafts&sr=1-4&ts_id=12897221',
    image1:'https://m.media-amazon.com/images/I/81N2XI3BtRL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/81WcAuRhydL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/81i1ihj3DFL._AC_SX679_.jpg',
    rating:'5.png',
    rating_text: 5,
    likes: 0,
    show: true,
    categoryId: 3,
    isDisabled: false
  },
  {
    id: 19,
    name: 'Acer Nitro 5 AN515-55-53E5 Gaming Laptop | Intel Core i5-10300H | NVIDIA GeForce RTX 3050 Laptop GPU | 15.6" FHD 144Hz IPS Display | 8GB DDR4 | 256GB NVMe SSD | Intel Wi-Fi 6 | Backlit Keyboard',
    price: 619,
    description: 'Dominate the Game: With the 10th Gen Intel Core i5-10300H processor, your Nitro 5 is packed with incredible power for all your games',
    url:'https://www.amazon.com/Acer-AN515-55-53E5-i5-10300H-GeForce-Keyboard/dp/B092YHJGMN/ref=sr_1_6?qid=1647187002&rnid=16225007011&s=computers-intl-ship&sr=1-6&th=1',
    image1:'https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/71gtHtMramS._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/71nim+DaEBS._AC_SX679_.jpg',
    rating:'4.5.png',
    rating_text: 4.5,
    likes: 0,
    show: true,
    categoryId: 4,
    isDisabled: false
  },
  {
    id: 20,
    name: 'HP 15-inch Laptop, 11th Generation Intel Core i5-1135G7, Intel Iris Xe Graphics, 8 GB RAM, 256 GB SSD, Windows 11 Home (15-dy2024nr, Natural silver)',
    price: 619,
    description: 'TAKE IT ANYWHERE – With its thin and light design, 6.5 millimeter micro-edge bezel display, and 82% screen to body ratio, you can take this PC anywhere and see more of what you love (1).',
    url:'https://www.amazon.com/HP-Generation-i5-1135G7-Graphics-15-dy2024nr/dp/B09FXFDGN3/ref=sr_1_8?qid=1647187002&rnid=16225007011&s=computers-intl-ship&sr=1-8',
    image1:'https://m.media-amazon.com/images/I/71RD3vsjIYL._AC_SX679_.jpg',
    image2:'https://m.media-amazon.com/images/I/71JL+uEoftL._AC_SX679_.jpg',
    image3:'https://m.media-amazon.com/images/I/71EHAHrIh9L._AC_SX679_.jpg',
    rating:'4.5.png',
    rating_text: 4.5,
    likes: 0,
    show: true,
    categoryId: 4,
    isDisabled: false
  }
];


/*
Copyright Google LLC. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at https://angular.io/license
*/